### ISSUE TITLE
Sort content by its category

### ISSUE THREAD

**Issue by diegologs** [bencodezen/vuepress-blog-boilerplate#22]
You have a folder to create post. I think is a better idea to have a folder called content. Inside thsi folder the user can create new folders to oder content automatically by his category.

For example if you create /content/posts/ and /content/notes/, automatically categorize the files within each folder without having to add within each file a variable with each category.

Then in the BlogPostList you can have a prop to pass a string with the category yo want to display for example category="notes" will render files inside /content/notes/ folder

**Comment by bencodezen** [comment]
@Frostqui Sorry for the delay in responding to this.

This seems like it would be better managed at the file level instead of the directory level. While this could be convenient from a convention perspective, I can see an issue where people may want to categorize files in multiple categories which would negate the folder approach.

I'm going to close this for now, but happy to entertain further discussion if you have some other ideas! Thanks for opening this issue and the suggestion!
