### ISSUE TITLE
Replacing homepage with Blog Post List page

### ISSUE THREAD

**Issue by kamicrafted** [bencodezen/vuepress-blog-boilerplate#48]
Hi Ben, thanks so much for your work on this. 

I've been trying to figure out a way to use the Posts page as the Homepage and haven't had much luck. (basically showing a list of x posts at the root domain rather than the static content that's currently the default).

Is this something that is possible currently? I'd imagine a lot of folks using this for their blog wanting to immediately serve up content rather than a splash/info page.

Any guidance you can provide would be much appreciated, thank you!

**Comment by cdvillard** [comment]
Do you have a repo we can look at? It's a little tricky to imagine this off
thentopnof the dome.

**Comment by kamicrafted** [comment]
Hi @cdvillard, the repo I'm working out of is here:
https://github.com/kamicrafted/blog

**Comment by kamicrafted** [comment]
@cdvillard were you able to take a look at my repo?

**Comment by bencodezen** [comment]
Hey @kamicrafted. Sorry for the delay in responding! This is totally possible and I will document this in the boilerplate. Basically, the easiest way to do this is to copy the code from `blog/README.md` into `src/README.md` so that your home page looks like this:

```
---
title: Blog
---

<BlogPostList 
  :pages="$site.pages" 
  :page-size="$site.themeConfig.pageSize" 
  :start-page="$site.themeConfig.startPage" 
/>
```

If you're wondering where the mechanics of this are, it is in the `src/.vuepress/theme/Layout.vue` where it toggles on the home page based on the `home` boolean frontmatter property. The `Blog` home page is actually just a default page with a global component in it.

I can definitely architect a better solution for this, but this should get you what you need for now. Let me know if you have any questions!

**Comment by bencodezen** [comment]
@kamicrafted Just added your question to the docs: 

https://vuepress-blog-boilerplate.bencodezen.io/learn/#why-is-this-separate-from-the-vuepress-repo

If you think the documentation is inadequate or you need additional clarification, please feel free to re-open the issue.

Thanks for your question and helping to make the boilerplate better!

**Comment by kamicrafted** [comment]
Amazing, thank you so much @bencodezen!

Worked like a charm. Doubly-awesome that you updated the docs to help others do the same :)
