### ISSUE TITLE
Custom pages using Vue templating instead of markdown

### ISSUE THREAD

**Issue by kamicrafted** [bencodezen/vuepress-blog-boilerplate#52]
What I'm trying to do is create a Photos page that displays items from an Instagram feed, using a combination of plugins and Vue templating.

The documentation currently makes it easy to spin up a static page using markdown, but doesn't seem to cover creating non-md driven pages. Is this even possible with Vuepress/Blog Boilerplate?

Guidance would be much appreciated!

**Comment by bencodezen** [comment]
@kamicrafted What a great question! You're totally right in that there is not a lot of documentation around creating non-MD centric pages.

I probably won't be able to build a prototype this weekend for you, but to at least get you something, there are two ideas in my head:

1. Create a script that would fetch the Instagram API and build static JSON / assets so that it is statically rendered. 

2. If we want it to be fetching live, then I would look into https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions which lets us use the `beforeMount` or `mounted` lifecycle hooks to use the async fetching against the Instagram API.

To prototype this, I would just go into `Layout.vue` to have it point to a new views component like `Instagram.vue` and then prototype it like you would any other SFC in a Vue.js app.

I'll be sure to try my own hand at this when a few of my deadlines are past, but let me know if you have any questions in the meantime and I'll do my best to assist you!

**Comment by kamicrafted** [comment]
@bencodezen Thanks for the suggestion, Ben! I'll tinker around and see how far I can get :)

I'm not sure if you meant `layout.vue` as I couldn't find a file named `Layers.vue`

Will share any progress I'm able to make back here.

**Comment by bencodezen** [comment]
@kamicrafted Wow. My bad. You are totally right. Haha. I meant `Layout.vue`
