### ISSUE TITLE
Error encoutering theme

### ISSUE THREAD

**Issue by ghost** [bencodezen/vuepress-blog-boilerplate#57]
[![asciicast](https://asciinema.org/a/284387.svg)](https://asciinema.org/a/284387)

There is an unknown error when running `vuepress dev`.
Some of the fonts on the website and also many pages are broken.

**Comment by jdot-santos** [comment]
I'm getting this same issue

**Comment by bencodezen** [comment]
Sorry about that @ryanccn and @jdot-santos. I am sorely behind on the technical debt for this project since I am working with the VuePress team to better document the blog-plugin as well as theming. 

I will try and release a new vuepress-blog-boilerplate asap though! Thank you for your patience and understanding in the meantime. 

If you have any other questions in the meantime, please don't hesitate to reach out!

**Comment by bencodezen** [comment]
Accidentally closed. I will absolutely look into this

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
